on:
  push:
     branches:
       - main
       - gh-pages

name: Deploy BrainEffeX app to shinyapps.io

jobs:
  deploy-shiny:
    name: Deploy to shinyapps.io
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.ACCESS_TOKEN }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        
    steps:
       - name: 🛎️ Checkout repository
         uses: actions/checkout@v2
         with:
           fetch-depth: 0
       - id: deploy
         name: 💎 Deploy to shinyapps.io
         uses: qwert666/shinyapps-actions@main
         env:
           SHINY_USERNAME: 'halleeshearer'
           SHINY_TOKEN: ${{ secrets.SHINYAPP_TOKEN }}
           SHINY_SECRET: ${{ secrets.SHINYAPP_SECRET }}
           APP_NAME: 'BrainEffeX_auto'
           APP_DIR: ''
